version: "3"

services:
  nginx:
    image: nginx:1.23-alpine
    ports:
      - "80:80"
      - "443:443"
    restart: always
    user: root
#    volumes:
#      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"

  db-p:
    image: postgres:17
    restart: always
    shm_size: 256mb
    # network_mode: host
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    volumes:
      - pg_data:/data/postgres

  rabbit:
    image: rabbitmq:4.0-management-alpine
    expose:
      - 5672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_LOGIN}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}
    ports:
      - "${RABBIT_PORT}:5672"
      - "${RABBIT_MONITOR_PORT}:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 3s
      timeout: 5s
      retries: 3

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_PATH=/bot/
    volumes:
      - ".:/bot"
    # network_mode: host
    command:
      /bin/sh -c "poetry run alembic upgrade head
      && poetry run python -Xfrozen_modules=off main.py"
    depends_on:
      - rabbit
      - db-p
      - nginx

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbit
    command:
      /bin/sh -c "poetry run taskiq scheduler infrastructure.scheduler:scheduler"
    volumes:
      - ".:/bot"
    restart: always

volumes:
  pg_data:
