version: '3'

tasks:
  reqs:
    cmds:
      - poetry install

  build:
    cmds:
      - docker compose --env-file .prod.env up -d --build

  recreate:
    cmds:
      - docker compose --env-file .prod.env up -d --force-recreate

  check:
    cmds:
      - pre-commit run --show-diff-on-failure --color=always --all-files

  update:
    cmds:
      - poetry update
      - pre-commit autoupdate

  build-wo-cache:
    cmds:
      - docker compose build --no-cache
      - docker compose --env-file .prod.env up -d

  down:
    cmds:
      - docker compose down -v
