version: '3'

tasks:
  reqs:
    cmds:
      - poetry install

  build:
    cmds:
      - docker compose --env-file .test.env up -d --build

  recreate:
    cmds:
      - docker compose --env-file .test.env up -d --force-recreate

  check:
    cmds:
      - pre-commit run --show-diff-on-failure --color=always --all-files

  update:
    cmds:
      - poetry update
      - pre-commit autoupdate
