"""added to prodcut model title

Revision ID: d5e4d34831da
Revises: 3e4a52d34924
Create Date: 2023-12-29 21:03:16.528801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e4d34831da'
down_revision: Union[str, None] = '3e4a52d34924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_User_ID', table_name='User')
    op.drop_table('User')
    op.drop_table('Product')
    op.drop_table('UserProduct')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserProduct',
    sa.Column('UserID', sa.BIGINT(), nullable=False),
    sa.Column('ProductID', sa.BIGINT(), nullable=False),
    sa.Column('PriceThreshold', sa.NUMERIC(), nullable=True),
    sa.Column('Added', sa.DATETIME(), nullable=False),
    sa.Column('Changed', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['ProductID'], ['Product.ID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['User.ID'], ),
    sa.PrimaryKeyConstraint('UserID', 'ProductID')
    )
    op.create_table('Product',
    sa.Column('ID', sa.BIGINT(), nullable=False),
    sa.Column('Price', sa.NUMERIC(), nullable=False),
    sa.Column('Img', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('User',
    sa.Column('ID', sa.BIGINT(), nullable=False),
    sa.Column('TZOffset', sa.SMALLINT(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('ix_User_ID', 'User', ['ID'], unique=False)
    # ### end Alembic commands ###
