"""prod add field mp-type

Revision ID: 0e470f2c4f78
Revises: 4ee8e981333c
Create Date: 2024-12-20 21:13:29.020851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e470f2c4f78'
down_revision: Union[str, None] = '4ee8e981333c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

mp_type = postgresql.ENUM('WB', 'OZON', name='mp_type_enum')

def upgrade() -> None:
    bind = op.get_bind()
    mp_type.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Product', sa.Column('MPType', mp_type, nullable=True))
    # ### end Alembic commands ###
    from infrastructure.db.models.product import Base, ProductModel, MPType
    metadata = Base.metadata

    session = sa.orm.Session(bind=bind)
    for prod in session.query(ProductModel):
        prod.MPType = MPType.WB
    session.commit()




def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Product', 'MPType')
    mp_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
