name: Docker Image CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: actions/checkout@v4

      - name: Ruff check
        run: |
          pwd
          pip install poetry
          pip install pre-commit
          poetry run pre-commit run --show-diff-on-failure --color=always --all-files


      - name: SSH App Deploy
        uses: kostyaten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          after_script: cd /root/projects/notifier-bot; git pull; task recreate
