name: Docker Image CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Server Deploy
        uses: kostyaten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          after_script: echo working          
