name: Docker Image CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x


      - name: Ruff check
        run: |
          cd /root/projects/notifier_bot
          task check


      - name: SSH App Deploy
        uses: kostyaten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          after_script: touch /root/projects/test.txt
